#pragma once

#define BLOCK_AIR 0
#define BLOCK_STONE 1
#define BLOCK_DIRT 2
#define BLOCK_GRASS 3
#define BLOCK_SAND 4
#define BLOCK_WATER 5
#define BLOCK_WATER_SURFACE 6
#define BLOCK_SNOW 7
#define BLOCK_OAK_LOG 8
#define BLOCK_OAK_LEAVES 9
#define BLOCK_TALL_GRASS 10
#define BLOCK_GRAVEL 11
#define BLOCK_FLOWER_RED 12
#define BLOCK_FLOWER_YELLOW 13