#pragma once

#define BLOCK_AIR 0
#define BLOCK_STONE 1
#define BLOCK_DIRT 2
#define BLOCK_GRASS 3
#define BLOCK_SAND 4
#define BLOCK_WATER 5
#define BLOCK_WATER_SURFACE 6
#define BLOCK_SNOW 7
#define BLOCK_OAK_LOG 8
#define BLOCK_OAK_LEAVES 9
#define BLOCK_TALL_GRASS 10
#define BLOCK_GRAVEL 11
#define BLOCK_FLOWER_RED 12
#define BLOCK_FLOWER_YELLOW 13
#define BLOCK_PODZOL 14

#define BLOCK_SEDGE 15
#define BLOCK_SEDGE_TOP 16
#define BLOCK_LILY_PAD 17
#define BLOCK_LILY_PADS 18
#define BLOCK_HUGE_GRASS 19
#define BLOCK_HUGE_GRASS_TOP 20
#define BLOCK_MUSHROOM_BROWN 21
#define BLOCK_MUSHROOM_RED 22
#define BLOCK_DEAD_LEAVES 23

#define BLOCK_SPEACIAL_FLOWER 24