#define ENABLE_FACE_CULLING true 
#define ENABLE_FRUSTRUM_CULLING false
#define ENABLE_CHUNK_EDGES false

#define BASIC_CHUNK_MESH_BULDING_STRATEGY 0
#define PER_CHUNK_OPTIMIZED_CHUNK_MESH_BUILDING_STRATEGY 1
#define OPTIMAL_CHUNK_MESH_BUILDING_STRATEGY 2
#define CHUNK_MESH_BUILDING_STRATEGY OPTIMAL_CHUNK_MESH_BUILDING_STRATEGY 

#define GENERATORS_COUNT 2
#define MESHERS_COUNT 2
#define REMESHERS_COUNT 2