#define ENABLE_FACE_CULLING true
#define ENABLE_FRUSTRUM_CULLING false
#define ENABLE_CHUNK_EDGES false

#define BASIC_CHUNK_MESH_BULDING_STRATEGY 0
#define PER_CHUNK_OPTIMIZED_CHUNK_MESH_BUILDING_STRATEGY 1
#define OPTIMAL_CHUNK_MESH_BUILDING_STRATEGY 2
#define CHUNK_MESH_BUILDING_STRATEGY OPTIMAL_CHUNK_MESH_BUILDING_STRATEGY

#define GENERATORS_COUNT 3
#define MESHERS_COUNT 4
#define REMESHERS_COUNT 2

#define RENDER_MESH_FANS false
#define CHUNKS_COUNT_TO_GENERATE 8

#define LOG_CAMERA false
#define ENABLE_DECORATIONS true
#define ENABLE_VEGETATION true
#define ENABLE_CAVES true

#define CAMERA_START_POSITION Vector(-140, 70, -4, 0)
#define CAMERA_START_YAW 360
#define CAMERA_START_PITCH -5
#define CAMERA_START_POV 65